os=require('os');
// tot=os.totalmem();
// tot=os.freemem();
// tot=os.tmpdir();
// tot=os.hostname();
// tot=os.type();
// tot=os.platform();
// tot=os.loadavg();
// tot=os.cpus();
tot=os.networkInterfaces();
console.log(tot);